"""
Chatbot/utils.py

Turns an uploaded Streamlit image + an image description (already
generated by a vision LLM call) into a plain-text HumanMessage. We
deliberately do NOT embed base64 image data into stored messages anymore -
only the text description of what the image contains gets persisted. This
keeps checkpoint_blobs small and means every message in Postgres is plain
text, which also means the summarizer can treat images just like any
other part of the conversation.
"""
import base64
from langchain_core.messages import HumanMessage


def build_human_message(text: str, image_description:str | None=None) -> HumanMessage:
    """
    text: what the user typed.
    image_description: text produced by a vision-model call describing an
                        uploaded image (or None if no image was attached).

    Returns a plain-string HumanMessage either way - no multimodal content
    blocks are stored. The image's *content* becomes part of the
    conversation as text; the image *file* itself is never saved.
    """
    if image_description is None:
        return HumanMessage(content=text)
    
    combined_text =(
        f"{text}\n\n"
        f"[Attached image - vision analysis: {image_description}]"
    )
    return HumanMessage(content=combined_text)




def message_text(msg) -> str:
    """Extract a display-friendly string from a message, whether its
    content is a plain string or a multimodal content-block list."""
    if isinstance(msg.content, str):
        return msg.content
    parts = []
    for block in msg.content:
        if isinstance(block, dict) and block.get("type") == "text":
            parts.append(block["text"])
    return "\n".join(parts) if parts else "[image]"


def message_has_image_note(msg) -> bool:
    """Detects whether a stored message includes an image analysis note,
    so the UI can show a small indicator on old messages."""
    text = message_text(msg)
    return "[Attached image" in text